//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwizSales.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en-IN")]
        public string Culture {
            get {
                return ((string)(this["Culture"]));
            }
            set {
                this["Culture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("`")]
        public string CurrencySymbol {
            get {
                return ((string)(this["CurrencySymbol"]));
            }
            set {
                this["CurrencySymbol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int CurrencyDecimalDigits {
            get {
                return ((int)(this["CurrencyDecimalDigits"]));
            }
            set {
                this["CurrencyDecimalDigits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TotalRoundOff {
            get {
                return ((bool)(this["TotalRoundOff"]));
            }
            set {
                this["TotalRoundOff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoPrint {
            get {
                return ((bool)(this["AutoPrint"]));
            }
            set {
                this["AutoPrint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double CustomerPointsAmount {
            get {
                return ((double)(this["CustomerPointsAmount"]));
            }
            set {
                this["CustomerPointsAmount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("303")]
        public double TicketWidth {
            get {
                return ((double)(this["TicketWidth"]));
            }
            set {
                this["TicketWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double TicketHeight {
            get {
                return ((double)(this["TicketHeight"]));
            }
            set {
                this["TicketHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1200")]
        public double ReportWidth {
            get {
                return ((double)(this["ReportWidth"]));
            }
            set {
                this["ReportWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1500")]
        public double ReportHeight {
            get {
                return ((double)(this["ReportHeight"]));
            }
            set {
                this["ReportHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TicketPrinter {
            get {
                return ((string)(this["TicketPrinter"]));
            }
            set {
                this["TicketPrinter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BarcodePrinter {
            get {
                return ((string)(this["BarcodePrinter"]));
            }
            set {
                this["BarcodePrinter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ReportPrinter {
            get {
                return ((string)(this["ReportPrinter"]));
            }
            set {
                this["ReportPrinter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int LineHeight {
            get {
                return ((int)(this["LineHeight"]));
            }
            set {
                this["LineHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public int ExtraHeight {
            get {
                return ((int)(this["ExtraHeight"]));
            }
            set {
                this["ExtraHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9dcd414d-156c-4465-89ed-095e5bb3d88a")]
        public global::System.Guid DefaultEmployeeId {
            get {
                return ((global::System.Guid)(this["DefaultEmployeeId"]));
            }
            set {
                this["DefaultEmployeeId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("b004dfc3-e53f-4e6b-952f-67ceae170da6")]
        public global::System.Guid DefaultCustomerId {
            get {
                return ((global::System.Guid)(this["DefaultCustomerId"]));
            }
            set {
                this["DefaultCustomerId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25125713-62be-4927-8623-b784c49cb01a")]
        public global::System.Guid DefaultCategoryId {
            get {
                return ((global::System.Guid)(this["DefaultCategoryId"]));
            }
            set {
                this["DefaultCategoryId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8cd9785e-f59c-4013-8c9c-fdde4b144738")]
        public global::System.Guid DefaultTaxCategoryId {
            get {
                return ((global::System.Guid)(this["DefaultTaxCategoryId"]));
            }
            set {
                this["DefaultTaxCategoryId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double PurchaseDiscount {
            get {
                return ((double)(this["PurchaseDiscount"]));
            }
            set {
                this["PurchaseDiscount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BackupFolderPath {
            get {
                return ((string)(this["BackupFolderPath"]));
            }
            set {
                this["BackupFolderPath"] = value;
            }
        }
    }
}
